<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BatDongSanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bat_dong_sans')->insertOrIgnore([
            [
                'tieu_de' => 'Chung cư mini 2 phòng ngủ Hải Châu',
                'mo_ta' => 'Căn hộ tầng đẹp, tầm nhìn không bị che khuất. Xung quanh nhiều mảng xanh, không khí trong lành. Phù hợp gia đình trẻ muốn ở gần trung tâm.',
                'gia' => 5000000000,
                'dien_tich' => 100,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 1,
                'dia_chi_id' => 1,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà riêng 2 tầng thuận tiện kinh doanh',
                'mo_ta' => 'Kiến trúc tân cổ điển, nội thất cơ bản đầy đủ. Đường trước nhà rộng rãi, xe ô tô ra vào thoải mái. Pháp lý chuẩn, sổ hồng hoàn công đầy đủ.',
                'gia' => 8000000000,
                'dien_tich' => 150,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 2,
                'dia_chi_id' => 2,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Đất quy hoạch đường rộng 7m5 khu dân cư',
                'mo_ta' => 'Mảnh đất bằng phẳng, vuông vức không bị xéo méo. Bán kính 1km có đầy đủ trường học, chợ, trung tâm y tế. Mức giá cực kỳ hấp dẫn cho các nhà đầu tư sinh lời.',
                'gia' => 2000000000,
                'dien_tich' => 200,
                'loai_id' => 4,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 3,
                'dia_chi_id' => 3,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư view thành phố gần sông Hàn',
                'mo_ta' => 'Chung cư được trang bị nội thất cơ bản, thiết kế thông minh tối ưu. Xung quanh nhiều mảng xanh, không khí trong lành. Rất tiện di chuyển ra các quận trung tâm và bãi biển.',
                'gia' => 3000000000,
                'dien_tich' => 80,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 4,
                'dia_chi_id' => 4,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự không gian mở đáng sống',
                'mo_ta' => 'Không gian sống xa hoa với hồ bơi riêng và khu vực BBQ ngoài trời. Cách bãi biển và các resort lớn chỉ vài phút lái xe. Cơ hội sở hữu bất động sản giá trị cao tại khu vực đắc địa.',
                'gia' => 15000000000,
                'dien_tich' => 300,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 1,
                'dia_chi_id' => 5,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự nội thất nhập khẩu khu biệt lập',
                'mo_ta' => 'Không gian sống xa hoa với hồ bơi riêng và khu vực BBQ ngoài trời. Môi trường sống trong lành, tách biệt hoàn toàn với ồn ào phố thị. Có sẵn hợp đồng thuê giá cao, dòng tiền ổn định.',
                'gia' => 4500000000,
                'dien_tich' => 180,
                'loai_id' => 3,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 2,
                'dia_chi_id' => 6,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 2,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Kho bãi khung thép tiền chế khu công nghiệp',
                'mo_ta' => 'Nền xưởng được đổ bê tông chịu tải trọng lớn, đánh bóng sạch sẽ. Khu vực tập trung nhiều cụm công nghiệp, dễ tuyển dụng lao động. Phù hợp làm nơi sản xuất, gia công hoặc kho chứa hàng hóa.',
                'gia' => 1500000000,
                'dien_tich' => 500,
                'loai_id' => 5,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 3,
                'dia_chi_id' => 7,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ studio thiết kế hiện đại gần sông Hàn',
                'mo_ta' => 'Không gian sống hiện đại với phòng khách liên thông bếp. Ban quản lý chuyên nghiệp, phí dịch vụ hợp lý. Sẵn sàng dọn vào ở ngay, giấy tờ pháp lý rõ ràng.',
                'gia' => 3500000000,
                'dien_tich' => 55,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 1,
                'dia_chi_id' => 8,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà nguyên căn 2 tầng an ninh đảm bảo',
                'mo_ta' => 'Nhà mới hoàn thiện, thiết kế theo phong cách hiện đại. Kết nối giao thông thuận tiện, đi đâu cũng gần. Thích hợp vừa ở vừa mở văn phòng công ty.',
                'gia' => 18000000000,
                'dien_tich' => 120,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 2,
                'dia_chi_id' => 9,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự sân vườn rộng đáng sống',
                'mo_ta' => 'Không gian sống xa hoa với hồ bơi riêng và khu vực BBQ ngoài trời. Cách bãi biển và các resort lớn chỉ vài phút lái xe. Sổ hồng trao tay, pháp lý minh bạch rõ ràng.',
                'gia' => 6500000000,
                'dien_tich' => 85,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 3,
                'dia_chi_id' => 10,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Đất thổ cư không lỗi phong thủy khu dân cư',
                'mo_ta' => 'Đất nền đã có sổ đỏ cá nhân, sẵn sàng công chứng sang tên. Đường phía trước rộng rãi, vỉa hè được lát gạch sạch đẹp. Tiềm năng tăng giá mạnh khi dự án lân cận triển khai.',
                'gia' => 4200000000,
                'dien_tich' => 150,
                'loai_id' => 4,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 4,
                'dia_chi_id' => 11,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Văn phòng view thành phố trung tâm',
                'mo_ta' => 'Mặt bằng có vách kính lớn đón ánh sáng và ngắm cảnh thành phố. Sảnh lễ tân sang trọng, có nhân viên đón khách nhiệt tình. Chi phí quản lý hợp lý, dịch vụ vệ sinh dọn dẹp hàng ngày.',
                'gia' => 30000000,
                'dien_tich' => 200,
                'loai_id' => 6,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 1,
                'dia_chi_id' => 12,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Khu đất sinh thái có sẵn ao cá gần hồ sinh thái',
                'mo_ta' => 'Mô hình vườn ao chuồng đã được thiết lập sẵn, hệ thống tưới tiêu tốt. Nguồn nước sạch dồi dào, hệ thống điện lưới quốc gia đã kéo vào tận nơi. Quỹ đất rộng rãi để thực hiện đam mê làm nông nghiệp sạch.',
                'gia' => 12000000000,
                'dien_tich' => 50000,
                'loai_id' => 8,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 2,
                'dia_chi_id' => 13,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Cửa hàng mặt tiền rộng gần trường học',
                'mo_ta' => 'Mặt bằng trống suốt từ trước ra sau, dễ dàng phân chia khu vực. Vỉa hè phía trước rộng thoáng, thoải mái đậu xe cho khách hàng. Hỗ trợ cọc linh hoạt, bàn giao ngay để tiến hành sửa chữa.',
                'gia' => 45000000,
                'dien_tich' => 90,
                'loai_id' => 7,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 3,
                'dia_chi_id' => 14,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ studio 2 phòng ngủ Đà Nẵng',
                'mo_ta' => 'Thiết kế tối giản, tông màu sáng tạo cảm giác rộng rãi. Khu vực xung quanh có đầy đủ tiện ích như siêu thị, quán ăn, trường học. Phù hợp gia đình trẻ muốn ở gần trung tâm.',
                'gia' => 4330000000,
                'dien_tich' => 91,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 21,
                'dia_chi_id' => 15,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ studio gần trung tâm Hải Châu',
                'mo_ta' => 'Không gian sống hiện đại với phòng khách liên thông bếp. Hệ thống an ninh 24/7, thang máy thẻ từ, bãi đỗ xe rộng rãi. Sẵn sàng dọn vào ở ngay, giấy tờ pháp lý rõ ràng.',
                'gia' => 4030000000,
                'dien_tich' => 116,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 25,
                'dia_chi_id' => 16,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự song lập compound an ninh đáng sống',
                'mo_ta' => 'Thiết kế hiện đại sang trọng, tối đa hóa không gian tiếp xúc thiên nhiên. Đường nội khu rộng rãi, trải nhựa sạch sẽ có vỉa hè. Cơ hội sở hữu bất động sản giá trị cao tại khu vực đắc địa.',
                'gia' => 13030000000,
                'dien_tich' => 87,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 45,
                'dia_chi_id' => 17,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư mini 2 phòng ngủ tiện ích đầy đủ',
                'mo_ta' => 'Căn hộ tầng đẹp, tầm nhìn không bị che khuất. Tòa nhà có hồ bơi, phòng gym và khu sinh hoạt chung. Lựa chọn lý tưởng cho chuyên gia làm việc tại Đà Nẵng.',
                'gia' => 5040000000,
                'dien_tich' => 118,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 30,
                'dia_chi_id' => 18,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư gần trung tâm gần sông Hàn',
                'mo_ta' => 'Căn hộ có ban công thoáng, đón gió tốt và ánh sáng tự nhiên. Xung quanh nhiều mảng xanh, không khí trong lành. Có thể kết hợp ở và cho thuê sinh lời tốt.',
                'gia' => 5900000000,
                'dien_tich' => 88,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 30,
                'dia_chi_id' => 19,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự mini không gian mở đáng sống',
                'mo_ta' => 'Không gian sống xa hoa với hồ bơi riêng và khu vực BBQ ngoài trời. Cách bãi biển và các resort lớn chỉ vài phút lái xe. Có sẵn hợp đồng thuê giá cao, dòng tiền ổn định.',
                'gia' => 13350000000,
                'dien_tich' => 338,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 21,
                'dia_chi_id' => 20,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Villa compound an ninh cao cấp',
                'mo_ta' => 'Thiết kế hiện đại sang trọng, tối đa hóa không gian tiếp xúc thiên nhiên. Môi trường sống trong lành, tách biệt hoàn toàn với ồn ào phố thị. Sự lựa chọn hoàn hảo để khẳng định đẳng cấp gia chủ.',
                'gia' => 11170000000,
                'dien_tich' => 307,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 45,
                'dia_chi_id' => 21,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư mini tầng trung gần sông Hàn',
                'mo_ta' => 'Chung cư được trang bị nội thất cơ bản, thiết kế thông minh tối ưu. Tòa nhà có hồ bơi, phòng gym và khu sinh hoạt chung. Có thể kết hợp ở và cho thuê sinh lời tốt.',
                'gia' => 1560000000,
                'dien_tich' => 117,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 42,
                'dia_chi_id' => 22,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư mini đón nắng tốt khu dân cư yên tĩnh',
                'mo_ta' => 'Không gian sống hiện đại với phòng khách liên thông bếp. Hệ thống an ninh 24/7, thang máy thẻ từ, bãi đỗ xe rộng rãi. Rất tiện di chuyển ra các quận trung tâm và bãi biển.',
                'gia' => 1500000000,
                'dien_tich' => 96,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 19,
                'dia_chi_id' => 23,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Văn phòng kính cường lực dễ tìm kiếm',
                'mo_ta' => 'Sàn đã được trải thảm, lắp sẵn điều hòa âm trần công suất lớn. Xung quanh tập trung nhiều ngân hàng, cơ quan hành chính. Chủ tòa nhà hỗ trợ nhiệt tình trong quá trình khách hàng thi công.',
                'gia' => 40000000,
                'dien_tich' => 135,
                'loai_id' => 6,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 5,
                'dia_chi_id' => 24,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ dịch vụ đón nắng tốt tiện ích đầy đủ',
                'mo_ta' => 'Thiết kế tối giản, tông màu sáng tạo cảm giác rộng rãi. Tòa nhà có hồ bơi, phòng gym và khu sinh hoạt chung. Có thể kết hợp ở và cho thuê sinh lời tốt.',
                'gia' => 1800000000,
                'dien_tich' => 115,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 38,
                'dia_chi_id' => 25,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà kiệt ô tô kiên cố gần trường học',
                'mo_ta' => 'Kiến trúc tân cổ điển, nội thất cơ bản đầy đủ. Nằm trong hẻm an ninh, yên tĩnh, không bị ngập nước. Khu vực tiềm năng tăng giá cao trong tương lai.',
                'gia' => 6250000000,
                'dien_tich' => 133,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 30,
                'dia_chi_id' => 26,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ cao cấp tầng trung Hải Châu',
                'mo_ta' => 'Chung cư được trang bị nội thất cơ bản, thiết kế thông minh tối ưu. Tòa nhà có hồ bơi, phòng gym và khu sinh hoạt chung. Phù hợp gia đình trẻ muốn ở gần trung tâm.',
                'gia' => 3190000000,
                'dien_tich' => 107,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 6,
                'dia_chi_id' => 27,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự compound an ninh đáng sống',
                'mo_ta' => 'Biệt thự có khoảng sân vườn rộng, trồng nhiều cây cảnh và tiểu cảnh. Đường nội khu rộng rãi, trải nhựa sạch sẽ có vỉa hè. Có sẵn hợp đồng thuê giá cao, dòng tiền ổn định.',
                'gia' => 19080000000,
                'dien_tich' => 233,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 36,
                'dia_chi_id' => 28,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự song lập sân vườn rộng khu biệt lập',
                'mo_ta' => 'Không gian sống xa hoa với hồ bơi riêng và khu vực BBQ ngoài trời. Môi trường sống trong lành, tách biệt hoàn toàn với ồn ào phố thị. Sự lựa chọn hoàn hảo để khẳng định đẳng cấp gia chủ.',
                'gia' => 21460000000,
                'dien_tich' => 150,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 46,
                'dia_chi_id' => 29,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Villa cách biển 500m đẳng cấp',
                'mo_ta' => 'Không gian sống xa hoa với hồ bơi riêng và khu vực BBQ ngoài trời. Môi trường sống trong lành, tách biệt hoàn toàn với ồn ào phố thị. Sổ hồng trao tay, pháp lý minh bạch rõ ràng.',
                'gia' => 10250000000,
                'dien_tich' => 131,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 5,
                'dia_chi_id' => 30,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Villa không gian mở khu biệt lập',
                'mo_ta' => 'Thiết kế hiện đại sang trọng, tối đa hóa không gian tiếp xúc thiên nhiên. Đường nội khu rộng rãi, trải nhựa sạch sẽ có vỉa hè. Sổ hồng trao tay, pháp lý minh bạch rõ ràng.',
                'gia' => 13260000000,
                'dien_tich' => 281,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 35,
                'dia_chi_id' => 31,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà nguyên căn kiên cố gần trường học',
                'mo_ta' => 'Nhà có khoảng sân trước rộng rãi để xe máy hoặc ô tô. Kết nối giao thông thuận tiện, đi đâu cũng gần. Rất phù hợp để gia đình đông người sinh sống lâu dài.',
                'gia' => 6160000000,
                'dien_tich' => 87,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 6,
                'dia_chi_id' => 32,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự thiết kế châu Âu đáng sống',
                'mo_ta' => 'Villa nghỉ dưỡng hoàn mỹ với các phòng ngủ master rộng lớn. Đường nội khu rộng rãi, trải nhựa sạch sẽ có vỉa hè. Không gian nghỉ dưỡng tuyệt vời cho gia đình vào dịp cuối tuần.',
                'gia' => 13010000000,
                'dien_tich' => 341,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 4,
                'dia_chi_id' => 33,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự song lập sân vườn rộng đáng sống',
                'mo_ta' => 'Biệt thự có khoảng sân vườn rộng, trồng nhiều cây cảnh và tiểu cảnh. Xung quanh là cộng đồng cư dân tinh hoa, dân trí cực cao. Có sẵn hợp đồng thuê giá cao, dòng tiền ổn định.',
                'gia' => 17620000000,
                'dien_tich' => 198,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 10,
                'dia_chi_id' => 34,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ studio full nội thất gần biển Mỹ Khê',
                'mo_ta' => 'Căn hộ tầng đẹp, tầm nhìn không bị che khuất. Ban quản lý chuyên nghiệp, phí dịch vụ hợp lý. Lựa chọn lý tưởng cho chuyên gia làm việc tại Đà Nẵng.',
                'gia' => 2080000000,
                'dien_tich' => 55,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 11,
                'dia_chi_id' => 35,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Mặt bằng kinh doanh nằm góc ngã tư khu đông dân cư',
                'mo_ta' => 'Shophouse hiện đại nằm dưới chân đế chung cư đông đúc. Vỉa hè phía trước rộng thoáng, thoải mái đậu xe cho khách hàng. Chủ nhà tạo điều kiện cho thuê dài hạn để khách yên tâm kinh doanh.',
                'gia' => 60000000,
                'dien_tich' => 144,
                'loai_id' => 7,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 37,
                'dia_chi_id' => 36,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư 2 phòng ngủ tiện ích đầy đủ',
                'mo_ta' => 'Căn hộ tầng đẹp, tầm nhìn không bị che khuất. Xung quanh nhiều mảng xanh, không khí trong lành. Sẵn sàng dọn vào ở ngay, giấy tờ pháp lý rõ ràng.',
                'gia' => 2890000000,
                'dien_tich' => 73,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 42,
                'dia_chi_id' => 37,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà mặt tiền phong thủy tốt an ninh đảm bảo',
                'mo_ta' => 'Nhà mới hoàn thiện, thiết kế theo phong cách hiện đại. Đường trước nhà rộng rãi, xe ô tô ra vào thoải mái. Pháp lý chuẩn, sổ hồng hoàn công đầy đủ.',
                'gia' => 5790000000,
                'dien_tich' => 168,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 10,
                'dia_chi_id' => 38,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà phố nội thất gỗ gần chợ',
                'mo_ta' => 'Nhà có khoảng sân trước rộng rãi để xe máy hoặc ô tô. Gần các trường học các cấp, bệnh viện và chợ truyền thống. Chủ nhà thiện chí, giao nhà ngay sau khi công chứng.',
                'gia' => 3980000000,
                'dien_tich' => 132,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 50,
                'dia_chi_id' => 39,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà nguyên căn 4 tầng gần chợ',
                'mo_ta' => 'Kiến trúc tân cổ điển, nội thất cơ bản đầy đủ. Đường trước nhà rộng rãi, xe ô tô ra vào thoải mái. Khu vực tiềm năng tăng giá cao trong tương lai.',
                'gia' => 13560000000,
                'dien_tich' => 61,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 3,
                'dia_chi_id' => 40,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Đất nền dự án đường 5m5 phù hợp đầu tư',
                'mo_ta' => 'Mảnh đất bằng phẳng, vuông vức không bị xéo méo. Đường phía trước rộng rãi, vỉa hè được lát gạch sạch đẹp. Hỗ trợ xin giấy phép xây dựng nhanh chóng cho khách mua.',
                'gia' => 5900000000,
                'dien_tich' => 159,
                'loai_id' => 4,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 4,
                'dia_chi_id' => 41,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự mini sân vườn rộng cao cấp',
                'mo_ta' => 'Biệt thự có khoảng sân vườn rộng, trồng nhiều cây cảnh và tiểu cảnh. Xung quanh là cộng đồng cư dân tinh hoa, dân trí cực cao. Sự lựa chọn hoàn hảo để khẳng định đẳng cấp gia chủ.',
                'gia' => 28150000000,
                'dien_tich' => 403,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 39,
                'dia_chi_id' => 42,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự nội thất nhập khẩu cao cấp',
                'mo_ta' => 'Thiết kế hiện đại sang trọng, tối đa hóa không gian tiếp xúc thiên nhiên. Cách bãi biển và các resort lớn chỉ vài phút lái xe. Cơ hội sở hữu bất động sản giá trị cao tại khu vực đắc địa.',
                'gia' => 34430000000,
                'dien_tich' => 204,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 18,
                'dia_chi_id' => 43,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự mini không gian mở đẳng cấp',
                'mo_ta' => 'Biệt thự có khoảng sân vườn rộng, trồng nhiều cây cảnh và tiểu cảnh. Nằm trong khu compound bảo vệ 24/24, camera giám sát toàn khu. Sổ hồng trao tay, pháp lý minh bạch rõ ràng.',
                'gia' => 12300000000,
                'dien_tich' => 324,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 21,
                'dia_chi_id' => 44,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư tầng trung gần sông Hàn',
                'mo_ta' => 'Chung cư được trang bị nội thất cơ bản, thiết kế thông minh tối ưu. Ban quản lý chuyên nghiệp, phí dịch vụ hợp lý. Rất tiện di chuyển ra các quận trung tâm và bãi biển.',
                'gia' => 4300000000,
                'dien_tich' => 119,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 26,
                'dia_chi_id' => 45,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Shophouse mặt tiền rộng gần khu văn phòng',
                'mo_ta' => 'Đã có sẵn hệ thống điện nước, cửa cuốn và kính cường lực. Vỉa hè phía trước rộng thoáng, thoải mái đậu xe cho khách hàng. Chủ nhà tạo điều kiện cho thuê dài hạn để khách yên tâm kinh doanh.',
                'gia' => 120000000,
                'dien_tich' => 147,
                'loai_id' => 7,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 8,
                'dia_chi_id' => 46,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Kho bãi đường xe cont đường lớn',
                'mo_ta' => 'Hệ thống nhà xưởng được xây dựng kiên cố, tiêu chuẩn cao. Đường vào xưởng rộng rãi, xe tải hoặc container quay đầu dễ dàng. Sẵn sàng bàn giao mặt bằng để doanh nghiệp đi vào hoạt động ngay.',
                'gia' => 60000000,
                'dien_tich' => 756,
                'loai_id' => 5,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 49,
                'dia_chi_id' => 47,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Đất quy hoạch không lỗi phong thủy gần trường',
                'mo_ta' => 'Đất nền đã có sổ đỏ cá nhân, sẵn sàng công chứng sang tên. Giao thông kết nối trực tiếp với các trục đường chính. Hỗ trợ xin giấy phép xây dựng nhanh chóng cho khách mua.',
                'gia' => 3430000000,
                'dien_tich' => 178,
                'loai_id' => 4,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 4,
                'dia_chi_id' => 48,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà kiệt ô tô vuông vức an ninh đảm bảo',
                'mo_ta' => 'Nhà mới hoàn thiện, thiết kế theo phong cách hiện đại. Khu dân cư đông đúc, dân trí cao, hàng xóm thân thiện. Khu vực tiềm năng tăng giá cao trong tương lai.',
                'gia' => 9790000000,
                'dien_tich' => 110,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 23,
                'dia_chi_id' => 49,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư 2 phòng ngủ gần sông Hàn',
                'mo_ta' => 'Không gian sống hiện đại với phòng khách liên thông bếp. Xung quanh nhiều mảng xanh, không khí trong lành. Phù hợp gia đình trẻ muốn ở gần trung tâm.',
                'gia' => 3200000000,
                'dien_tich' => 109,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 15,
                'dia_chi_id' => 50,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự mini sân vườn rộng yên tĩnh',
                'mo_ta' => 'Biệt thự có khoảng sân vườn rộng, trồng nhiều cây cảnh và tiểu cảnh. Môi trường sống trong lành, tách biệt hoàn toàn với ồn ào phố thị. Sự lựa chọn hoàn hảo để khẳng định đẳng cấp gia chủ.',
                'gia' => 8090000000,
                'dien_tich' => 333,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 10,
                'dia_chi_id' => 51,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà kho đường xe cont xe cộ lưu thông tốt',
                'mo_ta' => 'Hệ thống nhà xưởng được xây dựng kiên cố, tiêu chuẩn cao. Khu vực tập trung nhiều cụm công nghiệp, dễ tuyển dụng lao động. Có bảo vệ vòng ngoài đảm bảo an ninh hàng hóa.',
                'gia' => 80000000,
                'dien_tich' => 1735,
                'loai_id' => 5,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 17,
                'dia_chi_id' => 52,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ studio 2 phòng ngủ gần sông Hàn',
                'mo_ta' => 'Không gian sống hiện đại với phòng khách liên thông bếp. Hệ thống an ninh 24/7, thang máy thẻ từ, bãi đỗ xe rộng rãi. Có thể kết hợp ở và cho thuê sinh lời tốt.',
                'gia' => 5990000000,
                'dien_tich' => 65,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 18,
                'dia_chi_id' => 53,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự mini nội thất nhập khẩu yên tĩnh',
                'mo_ta' => 'Không gian sống xa hoa với hồ bơi riêng và khu vực BBQ ngoài trời. Đường nội khu rộng rãi, trải nhựa sạch sẽ có vỉa hè. Cơ hội sở hữu bất động sản giá trị cao tại khu vực đắc địa.',
                'gia' => 12920000000,
                'dien_tich' => 200,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 16,
                'dia_chi_id' => 54,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Sàn văn phòng kính cường lực dễ tìm kiếm',
                'mo_ta' => 'Không gian làm việc chuyên nghiệp với hệ thống chiếu sáng đạt chuẩn. Tòa nhà có thang máy tốc độ cao, máy phát điện dự phòng 100%. Chủ tòa nhà hỗ trợ nhiệt tình trong quá trình khách hàng thi công.',
                'gia' => 60000000,
                'dien_tich' => 215,
                'loai_id' => 6,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 5,
                'dia_chi_id' => 55,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Villa nghỉ dưỡng thiết kế châu Âu đẳng cấp',
                'mo_ta' => 'Biệt thự có khoảng sân vườn rộng, trồng nhiều cây cảnh và tiểu cảnh. Môi trường sống trong lành, tách biệt hoàn toàn với ồn ào phố thị. Cơ hội sở hữu bất động sản giá trị cao tại khu vực đắc địa.',
                'gia' => 32590000000,
                'dien_tich' => 224,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 23,
                'dia_chi_id' => 56,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Mặt bằng kho khung thép tiền chế xe cộ lưu thông tốt',
                'mo_ta' => 'Hệ thống nhà xưởng được xây dựng kiên cố, tiêu chuẩn cao. Nằm gần các tuyến giao thông huyết mạch thuận tiện vận chuyển. Phù hợp làm nơi sản xuất, gia công hoặc kho chứa hàng hóa.',
                'gia' => 80000000,
                'dien_tich' => 1398,
                'loai_id' => 5,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 2,
                'dia_chi_id' => 57,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ cao cấp tầng cao gần sông Hàn',
                'mo_ta' => 'Thiết kế tối giản, tông màu sáng tạo cảm giác rộng rãi. Hệ thống an ninh 24/7, thang máy thẻ từ, bãi đỗ xe rộng rãi. Sẵn sàng dọn vào ở ngay, giấy tờ pháp lý rõ ràng.',
                'gia' => 2920000000,
                'dien_tich' => 80,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 7,
                'dia_chi_id' => 58,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Khu đất sinh thái diện tích cực lớn gần hồ sinh thái',
                'mo_ta' => 'Cảnh quan thiên nhiên hoang sơ, hữu tình với suối nhỏ chảy qua. Hàng xóm xung quanh thân thiện, môi trường cực kỳ an ninh. Pháp lý rõ ràng, không tranh chấp, ranh giới được rào chắn cẩn thận.',
                'gia' => 3350000000,
                'dien_tich' => 13782,
                'loai_id' => 8,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 10,
                'dia_chi_id' => 59,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự song lập không gian mở cao cấp',
                'mo_ta' => 'Biệt thự có khoảng sân vườn rộng, trồng nhiều cây cảnh và tiểu cảnh. Cách bãi biển và các resort lớn chỉ vài phút lái xe. Sự lựa chọn hoàn hảo để khẳng định đẳng cấp gia chủ.',
                'gia' => 27640000000,
                'dien_tich' => 347,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 48,
                'dia_chi_id' => 60,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Đất nền dự án không lỗi phong thủy gần trường',
                'mo_ta' => 'Mảnh đất bằng phẳng, vuông vức không bị xéo méo. Nằm ngay trong khu dân cư hiện hữu, mật độ xây dựng cao. Mức giá cực kỳ hấp dẫn cho các nhà đầu tư sinh lời.',
                'gia' => 5050000000,
                'dien_tich' => 233,
                'loai_id' => 4,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 35,
                'dia_chi_id' => 61,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ studio view thành phố gần biển Mỹ Khê',
                'mo_ta' => 'Thiết kế tối giản, tông màu sáng tạo cảm giác rộng rãi. Khu vực xung quanh có đầy đủ tiện ích như siêu thị, quán ăn, trường học. Rất tiện di chuyển ra các quận trung tâm và bãi biển.',
                'gia' => 4790000000,
                'dien_tich' => 105,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 28,
                'dia_chi_id' => 62,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Sàn văn phòng tòa nhà chuyên nghiệp trung tâm',
                'mo_ta' => 'Sàn văn phòng vuông vức, ít cột, dễ dàng bố trí nội thất. Bãi đỗ xe dưới tầng hầm và xung quanh tòa nhà rất rộng rãi. Thời gian làm việc linh hoạt, hợp đồng thuê minh bạch.',
                'gia' => 30000000,
                'dien_tich' => 178,
                'loai_id' => 6,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 16,
                'dia_chi_id' => 63,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư full nội thất khu dân cư yên tĩnh',
                'mo_ta' => 'Không gian sống hiện đại với phòng khách liên thông bếp. Khu vực xung quanh có đầy đủ tiện ích như siêu thị, quán ăn, trường học. Có thể kết hợp ở và cho thuê sinh lời tốt.',
                'gia' => 4960000000,
                'dien_tich' => 114,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 12,
                'dia_chi_id' => 64,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Khu farmstay có sẵn ao cá giao thông tiện lợi',
                'mo_ta' => 'Bên trong có sẵn nhà cấp 4 nhỏ, ao nuôi cá và vườn cây ăn trái. Gần các khu du lịch nổi tiếng, tiềm năng thu hút khách dã ngoại cao. Thích hợp đầu tư mô hình farmstay hoặc khu cắm trại glamping.',
                'gia' => 18360000000,
                'dien_tich' => 12522,
                'loai_id' => 8,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 50,
                'dia_chi_id' => 65,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Villa nghỉ dưỡng sân vườn rộng cao cấp',
                'mo_ta' => 'Villa nghỉ dưỡng hoàn mỹ với các phòng ngủ master rộng lớn. Xung quanh là cộng đồng cư dân tinh hoa, dân trí cực cao. Có sẵn hợp đồng thuê giá cao, dòng tiền ổn định.',
                'gia' => 5900000000,
                'dien_tich' => 206,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 12,
                'dia_chi_id' => 66,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ thiết kế hiện đại khu dân cư yên tĩnh',
                'mo_ta' => 'Thiết kế tối giản, tông màu sáng tạo cảm giác rộng rãi. Ban quản lý chuyên nghiệp, phí dịch vụ hợp lý. Phù hợp gia đình trẻ muốn ở gần trung tâm.',
                'gia' => 2640000000,
                'dien_tich' => 46,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 25,
                'dia_chi_id' => 67,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Villa nội thất nhập khẩu khu biệt lập',
                'mo_ta' => 'Nội thất gỗ tự nhiên cao cấp, hệ thống điện thông minh toàn nhà. Xung quanh là cộng đồng cư dân tinh hoa, dân trí cực cao. Sổ hồng trao tay, pháp lý minh bạch rõ ràng.',
                'gia' => 10380000000,
                'dien_tich' => 490,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 45,
                'dia_chi_id' => 68,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự đơn lập cách biển 500m cao cấp',
                'mo_ta' => 'Không gian sống xa hoa với hồ bơi riêng và khu vực BBQ ngoài trời. Cách bãi biển và các resort lớn chỉ vài phút lái xe. Không gian nghỉ dưỡng tuyệt vời cho gia đình vào dịp cuối tuần.',
                'gia' => 33590000000,
                'dien_tich' => 389,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 50,
                'dia_chi_id' => 69,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ thiết kế hiện đại Hải Châu',
                'mo_ta' => 'Căn hộ có ban công thoáng, đón gió tốt và ánh sáng tự nhiên. Hệ thống an ninh 24/7, thang máy thẻ từ, bãi đỗ xe rộng rãi. Có thể kết hợp ở và cho thuê sinh lời tốt.',
                'gia' => 4370000000,
                'dien_tich' => 91,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 7,
                'dia_chi_id' => 70,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Villa view sông đáng sống',
                'mo_ta' => 'Biệt thự có khoảng sân vườn rộng, trồng nhiều cây cảnh và tiểu cảnh. Nằm trong khu compound bảo vệ 24/24, camera giám sát toàn khu. Cơ hội sở hữu bất động sản giá trị cao tại khu vực đắc địa.',
                'gia' => 32940000000,
                'dien_tich' => 379,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 13,
                'dia_chi_id' => 71,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự đơn lập compound an ninh không gian xanh',
                'mo_ta' => 'Biệt thự có khoảng sân vườn rộng, trồng nhiều cây cảnh và tiểu cảnh. Xung quanh là cộng đồng cư dân tinh hoa, dân trí cực cao. Cơ hội sở hữu bất động sản giá trị cao tại khu vực đắc địa.',
                'gia' => 7060000000,
                'dien_tich' => 404,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 18,
                'dia_chi_id' => 72,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Kiot thiết kế thông suốt gần khu văn phòng',
                'mo_ta' => 'Đã có sẵn hệ thống điện nước, cửa cuốn và kính cường lực. Lưu lượng giao thông qua lại mỗi ngày rất lớn, kinh doanh sầm uất. Cơ hội vàng để định vị thương hiệu tại tuyến đường sầm uất.',
                'gia' => 60000000,
                'dien_tich' => 154,
                'loai_id' => 7,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 29,
                'dia_chi_id' => 73,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự song lập thiết kế châu Âu đẳng cấp',
                'mo_ta' => 'Biệt thự có khoảng sân vườn rộng, trồng nhiều cây cảnh và tiểu cảnh. Xung quanh là cộng đồng cư dân tinh hoa, dân trí cực cao. Sổ hồng trao tay, pháp lý minh bạch rõ ràng.',
                'gia' => 22430000000,
                'dien_tich' => 238,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 49,
                'dia_chi_id' => 74,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Khu farmstay có sẵn ao cá không khí trong lành',
                'mo_ta' => 'Mô hình vườn ao chuồng đã được thiết lập sẵn, hệ thống tưới tiêu tốt. Hàng xóm xung quanh thân thiện, môi trường cực kỳ an ninh. Quỹ đất rộng rãi để thực hiện đam mê làm nông nghiệp sạch.',
                'gia' => 6060000000,
                'dien_tich' => 39845,
                'loai_id' => 8,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 22,
                'dia_chi_id' => 75,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà mới xây thiết kế hiện đại gần chợ',
                'mo_ta' => 'Kiến trúc tân cổ điển, nội thất cơ bản đầy đủ. Kết nối giao thông thuận tiện, đi đâu cũng gần. Thích hợp vừa ở vừa mở văn phòng công ty.',
                'gia' => 5330000000,
                'dien_tich' => 77,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 15,
                'dia_chi_id' => 76,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Villa nghỉ dưỡng view sông không gian xanh',
                'mo_ta' => 'Villa nghỉ dưỡng hoàn mỹ với các phòng ngủ master rộng lớn. Nằm trong khu compound bảo vệ 24/24, camera giám sát toàn khu. Có sẵn hợp đồng thuê giá cao, dòng tiền ổn định.',
                'gia' => 31080000000,
                'dien_tich' => 372,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 33,
                'dia_chi_id' => 77,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ studio view biển tiện ích đầy đủ',
                'mo_ta' => 'Chung cư được trang bị nội thất cơ bản, thiết kế thông minh tối ưu. Hệ thống an ninh 24/7, thang máy thẻ từ, bãi đỗ xe rộng rãi. Có thể kết hợp ở và cho thuê sinh lời tốt.',
                'gia' => 3380000000,
                'dien_tich' => 110,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 24,
                'dia_chi_id' => 78,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Đất nền dự án hai mặt tiền tiện xây nhà',
                'mo_ta' => 'Mảnh đất bằng phẳng, vuông vức không bị xéo méo. Giao thông kết nối trực tiếp với các trục đường chính. Hỗ trợ xin giấy phép xây dựng nhanh chóng cho khách mua.',
                'gia' => 6350000000,
                'dien_tich' => 133,
                'loai_id' => 4,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 12,
                'dia_chi_id' => 79,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự sân vườn rộng đẳng cấp',
                'mo_ta' => 'Biệt thự có khoảng sân vườn rộng, trồng nhiều cây cảnh và tiểu cảnh. Môi trường sống trong lành, tách biệt hoàn toàn với ồn ào phố thị. Sổ hồng trao tay, pháp lý minh bạch rõ ràng.',
                'gia' => 26210000000,
                'dien_tich' => 302,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 48,
                'dia_chi_id' => 80,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Mặt bằng thương mại thiết kế thông suốt khu đông dân cư',
                'mo_ta' => 'Mặt bằng trống suốt từ trước ra sau, dễ dàng phân chia khu vực. Vỉa hè phía trước rộng thoáng, thoải mái đậu xe cho khách hàng. Rất phù hợp kinh doanh thời trang, mỹ phẩm hoặc nhà thuốc.',
                'gia' => 30000000,
                'dien_tich' => 163,
                'loai_id' => 7,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 39,
                'dia_chi_id' => 81,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà kiệt ô tô mặt tiền rộng gần chợ',
                'mo_ta' => 'Nhà mới hoàn thiện, thiết kế theo phong cách hiện đại. Kết nối giao thông thuận tiện, đi đâu cũng gần. Chủ nhà thiện chí, giao nhà ngay sau khi công chứng.',
                'gia' => 6950000000,
                'dien_tich' => 107,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 29,
                'dia_chi_id' => 82,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Lô góc vuông vức phù hợp đầu tư',
                'mo_ta' => 'Nền đất cứng cáp, tiết kiệm chi phí làm móng khi xây dựng. Đường phía trước rộng rãi, vỉa hè được lát gạch sạch đẹp. Hỗ trợ xin giấy phép xây dựng nhanh chóng cho khách mua.',
                'gia' => 1550000000,
                'dien_tich' => 128,
                'loai_id' => 4,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 5,
                'dia_chi_id' => 83,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà riêng kiên cố khu dân cư yên tĩnh',
                'mo_ta' => 'Nhà có khoảng sân trước rộng rãi để xe máy hoặc ô tô. Nằm trong hẻm an ninh, yên tĩnh, không bị ngập nước. Pháp lý chuẩn, sổ hồng hoàn công đầy đủ.',
                'gia' => 6670000000,
                'dien_tich' => 121,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 19,
                'dia_chi_id' => 84,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ đón nắng tốt Đà Nẵng',
                'mo_ta' => 'Căn hộ tầng đẹp, tầm nhìn không bị che khuất. Hệ thống an ninh 24/7, thang máy thẻ từ, bãi đỗ xe rộng rãi. Phù hợp gia đình trẻ muốn ở gần trung tâm.',
                'gia' => 3200000000,
                'dien_tich' => 69,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 28,
                'dia_chi_id' => 85,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ studio view thành phố tiện ích đầy đủ',
                'mo_ta' => 'Căn hộ có ban công thoáng, đón gió tốt và ánh sáng tự nhiên. Tòa nhà có hồ bơi, phòng gym và khu sinh hoạt chung. Phù hợp gia đình trẻ muốn ở gần trung tâm.',
                'gia' => 5510000000,
                'dien_tich' => 100,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 24,
                'dia_chi_id' => 86,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ studio view biển gần biển Mỹ Khê',
                'mo_ta' => 'Căn hộ tầng đẹp, tầm nhìn không bị che khuất. Khu vực xung quanh có đầy đủ tiện ích như siêu thị, quán ăn, trường học. Có thể kết hợp ở và cho thuê sinh lời tốt.',
                'gia' => 3790000000,
                'dien_tich' => 101,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 50,
                'dia_chi_id' => 87,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Lô đất đường 5m5 khu dân cư',
                'mo_ta' => 'Nền đất cứng cáp, tiết kiệm chi phí làm móng khi xây dựng. Nằm ngay trong khu dân cư hiện hữu, mật độ xây dựng cao. Mức giá cực kỳ hấp dẫn cho các nhà đầu tư sinh lời.',
                'gia' => 2860000000,
                'dien_tich' => 212,
                'loai_id' => 4,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 23,
                'dia_chi_id' => 88,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ dịch vụ thiết kế hiện đại Sơn Trà',
                'mo_ta' => 'Căn hộ tầng đẹp, tầm nhìn không bị che khuất. Khu vực xung quanh có đầy đủ tiện ích như siêu thị, quán ăn, trường học. Sẵn sàng dọn vào ở ngay, giấy tờ pháp lý rõ ràng.',
                'gia' => 5960000000,
                'dien_tich' => 96,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 37,
                'dia_chi_id' => 89,
                'so_phong_ngu' => 1,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà phố 2 tầng gần trường học',
                'mo_ta' => 'Nhà xây đúc kiên cố, công năng bố trí hợp lý. Kết nối giao thông thuận tiện, đi đâu cũng gần. Thích hợp vừa ở vừa mở văn phòng công ty.',
                'gia' => 10970000000,
                'dien_tich' => 117,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 44,
                'dia_chi_id' => 90,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Đất thổ cư diện tích lớn phù hợp đầu tư',
                'mo_ta' => 'Mảnh đất bằng phẳng, vuông vức không bị xéo méo. Giao thông kết nối trực tiếp với các trục đường chính. Cam kết thông tin thật, giá cả thương lượng trực tiếp.',
                'gia' => 7760000000,
                'dien_tich' => 225,
                'loai_id' => 4,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 13,
                'dia_chi_id' => 91,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự song lập không gian mở khu biệt lập',
                'mo_ta' => 'Thiết kế hiện đại sang trọng, tối đa hóa không gian tiếp xúc thiên nhiên. Xung quanh là cộng đồng cư dân tinh hoa, dân trí cực cao. Cơ hội sở hữu bất động sản giá trị cao tại khu vực đắc địa.',
                'gia' => 13800000000,
                'dien_tich' => 452,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 13,
                'dia_chi_id' => 92,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 1,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà nguyên căn thiết kế hiện đại gần trường học',
                'mo_ta' => 'Không gian trong nhà rộng rãi, các phòng đều có cửa sổ. Kết nối giao thông thuận tiện, đi đâu cũng gần. Khu vực tiềm năng tăng giá cao trong tương lai.',
                'gia' => 11210000000,
                'dien_tich' => 165,
                'loai_id' => 2,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 40,
                'dia_chi_id' => 93,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 4,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ đón nắng tốt Sơn Trà',
                'mo_ta' => 'Thiết kế tối giản, tông màu sáng tạo cảm giác rộng rãi. Hệ thống an ninh 24/7, thang máy thẻ từ, bãi đỗ xe rộng rãi. Rất tiện di chuyển ra các quận trung tâm và bãi biển.',
                'gia' => 3030000000,
                'dien_tich' => 62,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 17,
                'dia_chi_id' => 94,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Kho bãi trần cao thuận tiện logistics',
                'mo_ta' => 'Không gian bên trong thông thoáng, trần cao không bị bí bách. Khu vực tập trung nhiều cụm công nghiệp, dễ tuyển dụng lao động. Sẵn sàng bàn giao mặt bằng để doanh nghiệp đi vào hoạt động ngay.',
                'gia' => 30000000,
                'dien_tich' => 1720,
                'loai_id' => 5,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 5,
                'dia_chi_id' => 95,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Shophouse sẵn kính cường lực khu đông dân cư',
                'mo_ta' => 'Shophouse hiện đại nằm dưới chân đế chung cư đông đúc. Mật độ dân số xung quanh cao, sức mua cực kỳ tốt. Hỗ trợ cọc linh hoạt, bàn giao ngay để tiến hành sửa chữa.',
                'gia' => 80000000,
                'dien_tich' => 144,
                'loai_id' => 7,
                'trang_thai_id' => 4,
                'moi_gioi_id' => 27,
                'dia_chi_id' => 96,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự đơn lập compound an ninh cao cấp',
                'mo_ta' => 'Không gian sống xa hoa với hồ bơi riêng và khu vực BBQ ngoài trời. Đường nội khu rộng rãi, trải nhựa sạch sẽ có vỉa hè. Sự lựa chọn hoàn hảo để khẳng định đẳng cấp gia chủ.',
                'gia' => 32720000000,
                'dien_tich' => 395,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 48,
                'dia_chi_id' => 97,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư thiết kế hiện đại khu dân cư yên tĩnh',
                'mo_ta' => 'Không gian sống hiện đại với phòng khách liên thông bếp. Khu vực xung quanh có đầy đủ tiện ích như siêu thị, quán ăn, trường học. Sẵn sàng dọn vào ở ngay, giấy tờ pháp lý rõ ràng.',
                'gia' => 4560000000,
                'dien_tich' => 51,
                'loai_id' => 1,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 25,
                'dia_chi_id' => 98,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 2,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự đơn lập thiết kế châu Âu khu biệt lập',
                'mo_ta' => 'Villa nghỉ dưỡng hoàn mỹ với các phòng ngủ master rộng lớn. Môi trường sống trong lành, tách biệt hoàn toàn với ồn ào phố thị. Không gian nghỉ dưỡng tuyệt vời cho gia đình vào dịp cuối tuần.',
                'gia' => 21400000000,
                'dien_tich' => 220,
                'loai_id' => 3,
                'trang_thai_id' => 2,
                'moi_gioi_id' => 49,
                'dia_chi_id' => 99,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 3,
                'is_duyet' => true,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà riêng 4 tầng thuận tiện kinh doanh',
                'mo_ta' => 'Không gian trong nhà rộng rãi, các phòng đều có cửa sổ. Đường trước nhà rộng rãi, xe ô tô ra vào thoải mái. Pháp lý chuẩn, sổ hồng hoàn công đầy đủ.',
                'gia' => 5060000000,
                'dien_tich' => 119,
                'loai_id' => 2,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 38,
                'dia_chi_id' => 100,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 3,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Villa nghỉ dưỡng thiết kế châu Âu yên tĩnh',
                'mo_ta' => 'Biệt thự có khoảng sân vườn rộng, trồng nhiều cây cảnh và tiểu cảnh. Đường nội khu rộng rãi, trải nhựa sạch sẽ có vỉa hè. Sự lựa chọn hoàn hảo để khẳng định đẳng cấp gia chủ.',
                'gia' => 7640000000,
                'dien_tich' => 353,
                'loai_id' => 3,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 35,
                'dia_chi_id' => 101,
                'so_phong_ngu' => 4,
                'so_phong_tam' => 3,
                'is_duyet' => false,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ studio đón nắng tốt gần sông Hàn',
                'mo_ta' => 'Căn hộ tầng đẹp, tầm nhìn không bị che khuất. Xung quanh nhiều mảng xanh, không khí trong lành. Lựa chọn lý tưởng cho chuyên gia làm việc tại Đà Nẵng.',
                'gia' => 1880000000,
                'dien_tich' => 49,
                'loai_id' => 1,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 31,
                'dia_chi_id' => 102,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 3,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ tầng cao Sơn Trà',
                'mo_ta' => 'Căn hộ có ban công thoáng, đón gió tốt và ánh sáng tự nhiên. Tòa nhà có hồ bơi, phòng gym và khu sinh hoạt chung. Có thể kết hợp ở và cho thuê sinh lời tốt.',
                'gia' => 4140000000,
                'dien_tich' => 90,
                'loai_id' => 1,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 29,
                'dia_chi_id' => 103,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 4,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nhà riêng 3 tầng an ninh đảm bảo',
                'mo_ta' => 'Nhà mới hoàn thiện, thiết kế theo phong cách hiện đại. Khu dân cư đông đúc, dân trí cao, hàng xóm thân thiện. Chủ nhà thiện chí, giao nhà ngay sau khi công chứng.',
                'gia' => 13750000000,
                'dien_tich' => 173,
                'loai_id' => 2,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 41,
                'dia_chi_id' => 104,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 3,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư mini tầng cao Sơn Trà',
                'mo_ta' => 'Không gian sống hiện đại với phòng khách liên thông bếp. Hệ thống an ninh 24/7, thang máy thẻ từ, bãi đỗ xe rộng rãi. Lựa chọn lý tưởng cho chuyên gia làm việc tại Đà Nẵng.',
                'gia' => 3420000000,
                'dien_tich' => 49,
                'loai_id' => 1,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 9,
                'dia_chi_id' => 105,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 1,
                'is_duyet' => false,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Kho bãi đường xe cont gần quốc lộ',
                'mo_ta' => 'Không gian bên trong thông thoáng, trần cao không bị bí bách. Trạm biến áp riêng biệt, đảm bảo nguồn điện sản xuất liên tục. Có bảo vệ vòng ngoài đảm bảo an ninh hàng hóa.',
                'gia' => 90000000,
                'dien_tich' => 1344,
                'loai_id' => 5,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 22,
                'dia_chi_id' => 106,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Chung cư ban công thoáng gần biển Mỹ Khê',
                'mo_ta' => 'Thiết kế tối giản, tông màu sáng tạo cảm giác rộng rãi. Xung quanh nhiều mảng xanh, không khí trong lành. Rất tiện di chuyển ra các quận trung tâm và bãi biển.',
                'gia' => 4920000000,
                'dien_tich' => 119,
                'loai_id' => 1,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 42,
                'dia_chi_id' => 107,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 2,
                'is_duyet' => false,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ dịch vụ thiết kế hiện đại gần biển Mỹ Khê',
                'mo_ta' => 'Chung cư được trang bị nội thất cơ bản, thiết kế thông minh tối ưu. Hệ thống an ninh 24/7, thang máy thẻ từ, bãi đỗ xe rộng rãi. Sẵn sàng dọn vào ở ngay, giấy tờ pháp lý rõ ràng.',
                'gia' => 3770000000,
                'dien_tich' => 91,
                'loai_id' => 1,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 23,
                'dia_chi_id' => 108,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 3,
                'is_duyet' => false,
                'is_noi_bat' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Biệt thự view sông khu biệt lập',
                'mo_ta' => 'Villa nghỉ dưỡng hoàn mỹ với các phòng ngủ master rộng lớn. Môi trường sống trong lành, tách biệt hoàn toàn với ồn ào phố thị. Sự lựa chọn hoàn hảo để khẳng định đẳng cấp gia chủ.',
                'gia' => 27490000000,
                'dien_tich' => 432,
                'loai_id' => 3,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 46,
                'dia_chi_id' => 109,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 3,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ dịch vụ ban công thoáng gần sông Hàn',
                'mo_ta' => 'Căn hộ có ban công thoáng, đón gió tốt và ánh sáng tự nhiên. Khu vực xung quanh có đầy đủ tiện ích như siêu thị, quán ăn, trường học. Lựa chọn lý tưởng cho chuyên gia làm việc tại Đà Nẵng.',
                'gia' => 5070000000,
                'dien_tich' => 77,
                'loai_id' => 1,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 25,
                'dia_chi_id' => 110,
                'so_phong_ngu' => 3,
                'so_phong_tam' => 2,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Lô đất diện tích lớn gần trường',
                'mo_ta' => 'Mảnh đất bằng phẳng, vuông vức không bị xéo méo. Bán kính 1km có đầy đủ trường học, chợ, trung tâm y tế. Cam kết thông tin thật, giá cả thương lượng trực tiếp.',
                'gia' => 6530000000,
                'dien_tich' => 178,
                'loai_id' => 4,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 45,
                'dia_chi_id' => 111,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Villa sân vườn rộng khu biệt lập',
                'mo_ta' => 'Thiết kế hiện đại sang trọng, tối đa hóa không gian tiếp xúc thiên nhiên. Cách bãi biển và các resort lớn chỉ vài phút lái xe. Không gian nghỉ dưỡng tuyệt vời cho gia đình vào dịp cuối tuần.',
                'gia' => 11520000000,
                'dien_tich' => 390,
                'loai_id' => 3,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 22,
                'dia_chi_id' => 112,
                'so_phong_ngu' => 2,
                'so_phong_tam' => 4,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Khu farmstay diện tích cực lớn không khí trong lành',
                'mo_ta' => 'Mô hình vườn ao chuồng đã được thiết lập sẵn, hệ thống tưới tiêu tốt. Hàng xóm xung quanh thân thiện, môi trường cực kỳ an ninh. Pháp lý rõ ràng, không tranh chấp, ranh giới được rào chắn cẩn thận.',
                'gia' => 19770000000,
                'dien_tich' => 16650,
                'loai_id' => 8,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 30,
                'dia_chi_id' => 113,
                'so_phong_ngu' => null,
                'so_phong_tam' => null,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Căn hộ studio ban công thoáng gần biển Mỹ Khê',
                'mo_ta' => 'Không gian sống hiện đại với phòng khách liên thông bếp. Tòa nhà có hồ bơi, phòng gym và khu sinh hoạt chung. Sẵn sàng dọn vào ở ngay, giấy tờ pháp lý rõ ràng.',
                'gia' => 4040000000,
                'dien_tich' => 93,
                'loai_id' => 1,
                'trang_thai_id' => 1,
                'moi_gioi_id' => 50,
                'dia_chi_id' => 114,
                'so_phong_ngu' => 5,
                'so_phong_tam' => 2,
                'is_duyet' => false,
                'is_noi_bat' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
