<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiaChiSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('dia_chis')->insert([
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 24,
                'dia_chi_chi_tiet' => '816 Nguyễn Tri Phương',
                'latitude' => 16.079987,
                'longitude' => 108.219926,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 36,
                'dia_chi_chi_tiet' => '746 An Thượng',
                'latitude' => 16.04763,
                'longitude' => 108.234668,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 57,
                'dia_chi_chi_tiet' => '299 Vành Đai Phía Tây',
                'latitude' => 15.966335,
                'longitude' => 108.166951,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 36,
                'dia_chi_chi_tiet' => '62 Lê Văn Hiến',
                'latitude' => 16.053552,
                'longitude' => 108.232284,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 43,
                'dia_chi_chi_tiet' => '3 Xô Viết Nghệ Tĩnh',
                'latitude' => 16.005678,
                'longitude' => 108.204279,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 2,
                'phuong_xa_id' => 10,
                'dia_chi_chi_tiet' => '925 Điện Biên Phủ',
                'latitude' => 16.062299,
                'longitude' => 108.184794,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 21,
                'dia_chi_chi_tiet' => '943 Quang Trung',
                'latitude' => 16.066036,
                'longitude' => 108.215451,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 2,
                'phuong_xa_id' => 8,
                'dia_chi_chi_tiet' => '470 Nguyễn Phước Nguyên',
                'latitude' => 16.066740,
                'longitude' => 108.190880,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 43,
                'dia_chi_chi_tiet' => '987 Cách Mạng Tháng 8',
                'latitude' => 16.005457,
                'longitude' => 108.205559,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 41,
                'dia_chi_chi_tiet' => '691 Nguyễn Hữu Thọ',
                'latitude' => 16.043474,
                'longitude' => 108.202266,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 2,
                'phuong_xa_id' => 10,
                'dia_chi_chi_tiet' => '582 Nguyễn Phước Nguyên',
                'latitude' => 16.081492,
                'longitude' => 108.206862,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 5,
                'dia_chi_chi_tiet' => '453 Lạc Long Quân',
                'latitude' => 16.074843,
                'longitude' => 108.1432976,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 43,
                'dia_chi_chi_tiet' => '322 Lê Đại Hành',
                'latitude' => 16.030567,
                'longitude' => 108.190858,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 32,
                'dia_chi_chi_tiet' => '818 Vương Thừa Vũ',
                'latitude' => 16.094855,
                'longitude' => 108.242691,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 38,
                'dia_chi_chi_tiet' => '555 Võ Chí Công',
                'latitude' => 16.042489,
                'longitude' => 108.235906,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 39,
                'dia_chi_chi_tiet' => '244 Hồ Xuân Hương',
                'latitude' => 16.009996,
                'longitude' => 108.225431,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 28,
                'dia_chi_chi_tiet' => '323 Ông Ích Khiêm',
                'latitude' => 16.048293,
                'longitude' => 108.212844,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 45,
                'dia_chi_chi_tiet' => '855 Ông Ích Đường',
                'latitude' => 16.033494,
                'longitude' => 108.223751,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 42,
                'dia_chi_chi_tiet' => '898 Lê Đại Hành',
                'latitude' => 16.030294,
                'longitude' => 108.181832,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 4,
                'dia_chi_chi_tiet' => '97 Hoàng Văn Thái',
                'latitude' => 16.070187,
                'longitude' => 108.155068,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 38,
                'dia_chi_chi_tiet' => '1 Minh Mạng',
                'latitude' => 16.030261,
                'longitude' => 108.229596,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 52,
                'dia_chi_chi_tiet' => '948 Quốc lộ 1A',
                'latitude' => 16.059649,
                'longitude' => 108.169344,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 21,
                'dia_chi_chi_tiet' => '461 Nguyễn Văn Linh',
                'latitude' => 16.045305,
                'longitude' => 108.227328,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 36,
                'dia_chi_chi_tiet' => '578 Minh Mạng',
                'latitude' => 16.054068,
                'longitude' => 108.243179,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 45,
                'dia_chi_chi_tiet' => '306 Võ An Ninh',
                'latitude' => 16.022035,
                'longitude' => 108.207191,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 20,
                'dia_chi_chi_tiet' => '165 Hoàng Diệu',
                'latitude' => 16.050426,
                'longitude' => 108.214807,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 41,
                'dia_chi_chi_tiet' => '808 Trường Chinh',
                'latitude' => 16.042598,
                'longitude' => 108.189924,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 33,
                'dia_chi_chi_tiet' => '931 Nguyễn Công Trứ',
                'latitude' => 16.075299,
                'longitude' => 108.239831,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 48,
                'dia_chi_chi_tiet' => '686 Quốc lộ 14B',
                'latitude' => 16.036759,
                'longitude' => 108.093704,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 2,
                'dia_chi_chi_tiet' => '342 Hoàng Văn Thái',
                'latitude' => 16.074850,
                'longitude' => 108.128940,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 2,
                'phuong_xa_id' => 7,
                'dia_chi_chi_tiet' => '877 Điện Biên Phủ',
                'latitude' => 16.075221,
                'longitude' => 108.180751,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 33,
                'dia_chi_chi_tiet' => '24 Ngô Quyền',
                'latitude' => 16.058612,
                'longitude' => 108.235541,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 3,
                'dia_chi_chi_tiet' => '591 Lạc Long Quân',
                'latitude' => 16.066961,
                'longitude' => 108.122717,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 31,
                'dia_chi_chi_tiet' => '592 Vương Thừa Vũ',
                'latitude' => 16.063568,
                'longitude' => 108.234967,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 36,
                'dia_chi_chi_tiet' => '398 Trần Đại Nghĩa',
                'latitude' => 16.026734,
                'longitude' => 108.226235,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 52,
                'dia_chi_chi_tiet' => '788 Đường số 1 KCN',
                'latitude' => 16.050156,
                'longitude' => 108.136368,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 56,
                'dia_chi_chi_tiet' => '511 Đường số 2 KCN',
                'latitude' => 15.95968,
                'longitude' => 108.165586,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 18,
                'dia_chi_chi_tiet' => '86 Nguyễn Văn Linh',
                'latitude' => 16.056307,
                'longitude' => 108.217706,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 33,
                'dia_chi_chi_tiet' => '35 Lê Văn Thứ',
                'latitude' => 16.071295,
                'longitude' => 108.236466,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 39,
                'dia_chi_chi_tiet' => '891 Lê Văn Hiến',
                'latitude' => 16.023451,
                'longitude' => 108.244599,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 40,
                'dia_chi_chi_tiet' => '303 Đô Đốc Lân',
                'latitude' => 16.014003,
                'longitude' => 108.202605,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 2,
                'phuong_xa_id' => 11,
                'dia_chi_chi_tiet' => '24 Lê Độ',
                'latitude' => 16.072365,
                'longitude' => 108.194431,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 2,
                'phuong_xa_id' => 10,
                'dia_chi_chi_tiet' => '591 Huỳnh Ngọc Huệ',
                'latitude' => 16.070180,
                'longitude' => 108.184920,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 47,
                'dia_chi_chi_tiet' => '285 Quốc lộ 1A',
                'latitude' => 16.113240,
                'longitude' => 108.129850,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 2,
                'phuong_xa_id' => 10,
                'dia_chi_chi_tiet' => '123 Trần Cao Vân',
                'latitude' => 16.071840,
                'longitude' => 108.190260,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 3,
                'dia_chi_chi_tiet' => '14 Lạc Long Quân',
                'latitude' => 16.0753926,
                'longitude' => 108.1456153,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 47,
                'dia_chi_chi_tiet' => '29 Đường số 2 KCN',
                'latitude' => 16.026345,
                'longitude' => 108.0915,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 4,
                'dia_chi_chi_tiet' => '76 Mẹ Suốt',
                'latitude' => 16.0579316,
                'longitude' => 108.1566976,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 44,
                'dia_chi_chi_tiet' => '753 Đô Đốc Lân',
                'latitude' => 16.043599,
                'longitude' => 108.22487,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 33,
                'dia_chi_chi_tiet' => '448 Hồ Nghinh',
                'latitude' => 16.07335,
                'longitude' => 108.243564,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 50,
                'dia_chi_chi_tiet' => '475 Âu Cơ nối dài',
                'latitude' => 15.997086,
                'longitude' => 108.182947,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 47,
                'dia_chi_chi_tiet' => '237 Quốc lộ 1A',
                'latitude' => 15.994084,
                'longitude' => 108.126117,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 2,
                'phuong_xa_id' => 8,
                'dia_chi_chi_tiet' => '793 Nguyễn Tất Thành',
                'latitude' => 16.059032,
                'longitude' => 108.181509,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 39,
                'dia_chi_chi_tiet' => '9 Trần Đại Nghĩa',
                'latitude' => 16.053632,
                'longitude' => 108.243607,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 37,
                'dia_chi_chi_tiet' => '198 Nam Kỳ Khởi Nghĩa',
                'latitude' => 16.054733,
                'longitude' => 108.240908,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 1,
                'dia_chi_chi_tiet' => '848 Nguyễn Lương Bằng',
                'latitude' => 16.068894,
                'longitude' => 108.159874,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 50,
                'dia_chi_chi_tiet' => '747 Vành Đai Phía Tây',
                'latitude' => 16.019491,
                'longitude' => 108.077548,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 3,
                'dia_chi_chi_tiet' => '437 Mẹ Suốt',
                'latitude' => 16.074153,
                'longitude' => 108.131413,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 36,
                'dia_chi_chi_tiet' => '975 An Thượng',
                'latitude' => 16.022484,
                'longitude' => 108.247461,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 4,
                'dia_chi_chi_tiet' => '208 Nguyễn Sinh Sắc',
                'latitude' => 16.083920,
                'longitude' => 108.151480,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 55,
                'dia_chi_chi_tiet' => '147 Quốc lộ 14B',
                'latitude' => 15.999688,
                'longitude' => 108.188995,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 25,
                'dia_chi_chi_tiet' => '98 Trần Phú',
                'latitude' => 16.049423,
                'longitude' => 108.209042,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 55,
                'dia_chi_chi_tiet' => '609 Quốc lộ 1A',
                'latitude' => 16.00832,
                'longitude' => 108.106171,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 5,
                'dia_chi_chi_tiet' => '9 Âu Cơ',
                'latitude' => 16.077857,
                'longitude' => 108.169203,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 36,
                'dia_chi_chi_tiet' => '123 Võ Chí Công',
                'latitude' => 16.044128,
                'longitude' => 108.244719,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 54,
                'dia_chi_chi_tiet' => '410 Đường số 2 KCN',
                'latitude' => 15.988433,
                'longitude' => 108.105861,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 45,
                'dia_chi_chi_tiet' => '765 Tôn Đản',
                'latitude' => 16.014426,
                'longitude' => 108.199278,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 4,
                'dia_chi_chi_tiet' => '898 Phạm Như Xương',
                'latitude' => 16.077320,
                'longitude' => 108.154370,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 2,
                'dia_chi_chi_tiet' => '810 Nguyễn Lương Bằng',
                'latitude' => 16.087910,
                'longitude' => 108.140760,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 21,
                'dia_chi_chi_tiet' => '37 Nguyễn Tri Phương',
                'latitude' => 16.060285,
                'longitude' => 108.210481,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 39,
                'dia_chi_chi_tiet' => '657 Nam Kỳ Khởi Nghĩa',
                'latitude' => 16.018506,
                'longitude' => 108.233492,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 46,
                'dia_chi_chi_tiet' => '796 Quốc lộ 14B',
                'latitude' => 16.015336,
                'longitude' => 108.17237,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 53,
                'dia_chi_chi_tiet' => '345 Đường số 2 KCN',
                'latitude' => 15.995369,
                'longitude' => 108.117611,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 34,
                'dia_chi_chi_tiet' => '380 Hồ Nghinh',
                'latitude' => 16.055432,
                'longitude' => 108.225749,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 2,
                'dia_chi_chi_tiet' => '817 Nguyễn Lương Bằng',
                'latitude' => 16.116113,
                'longitude' => 108.124529,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 50,
                'dia_chi_chi_tiet' => '24 Quốc lộ 1A',
                'latitude' => 15.987645,
                'longitude' => 108.152732,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 37,
                'dia_chi_chi_tiet' => '80 Châu Thị Vĩnh Tế',
                'latitude' => 16.033048,
                'longitude' => 108.23671,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 51,
                'dia_chi_chi_tiet' => '446 Âu Cơ nối dài',
                'latitude' => 16.005265,
                'longitude' => 108.093924,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 31,
                'dia_chi_chi_tiet' => '977 Ngô Quyền',
                'latitude' => 16.092616,
                'longitude' => 108.238849,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 30,
                'dia_chi_chi_tiet' => '719 Dương Đình Nghệ',
                'latitude' => 16.058354,
                'longitude' => 108.231705,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 42,
                'dia_chi_chi_tiet' => '159 Cách Mạng Tháng 8',
                'latitude' => 16.044287,
                'longitude' => 108.187786,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 34,
                'dia_chi_chi_tiet' => '893 Ngô Quyền',
                'latitude' => 16.078299,
                'longitude' => 108.237098,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 16,
                'dia_chi_chi_tiet' => '364 Đống Đa',
                'latitude' => 16.048699,
                'longitude' => 108.228543,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 22,
                'dia_chi_chi_tiet' => '654 Trần Phú',
                'latitude' => 16.071307,
                'longitude' => 108.206314,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 2,
                'phuong_xa_id' => 7,
                'dia_chi_chi_tiet' => '635 Hà Huy Tập',
                'latitude' => 16.059809,
                'longitude' => 108.175439,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 35,
                'dia_chi_chi_tiet' => '193 Nguyễn Công Trứ',
                'latitude' => 16.082864,
                'longitude' => 108.234508,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 2,
                'dia_chi_chi_tiet' => '405 Kinh Dương Vương',
                'latitude' => 16.118073,
                'longitude' => 108.12981,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 38,
                'dia_chi_chi_tiet' => '351 Châu Thị Vĩnh Tế',
                'latitude' => 16.052246,
                'longitude' => 108.227995,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 5,
                'dia_chi_chi_tiet' => '941 Tôn Đức Thắng',
                'latitude' => 16.078620,
                'longitude' => 108.165310,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 18,
                'dia_chi_chi_tiet' => '514 2 Tháng 9',
                'latitude' => 16.054069,
                'longitude' => 108.218889,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 56,
                'dia_chi_chi_tiet' => '990 Đường số 2 KCN',
                'latitude' => 15.959476,
                'longitude' => 108.187963,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 56,
                'dia_chi_chi_tiet' => '56 Vành Đai Phía Tây',
                'latitude' => 15.958242,
                'longitude' => 108.159802,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 41,
                'dia_chi_chi_tiet' => '874 Xô Viết Nghệ Tĩnh',
                'latitude' => 16.020698,
                'longitude' => 108.215513,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 43,
                'dia_chi_chi_tiet' => '890 Tôn Đản',
                'latitude' => 16.033922,
                'longitude' => 108.187969,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 4,
                'dia_chi_chi_tiet' => '100 Nguyễn Sinh Sắc',
                'latitude' => 16.0742162,
                'longitude' => 108.1608141,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 47,
                'dia_chi_chi_tiet' => '814 ĐT602',
                'latitude' => 15.975704,
                'longitude' => 108.170122,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 50,
                'dia_chi_chi_tiet' => '711 Quốc lộ 1A',
                'latitude' => 15.997042,
                'longitude' => 108.083056,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 35,
                'dia_chi_chi_tiet' => '881 Dương Đình Nghệ',
                'latitude' => 16.070026,
                'longitude' => 108.231064,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 22,
                'dia_chi_chi_tiet' => '793 Nguyễn Tri Phương',
                'latitude' => 16.077306,
                'longitude' => 108.219791,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 25,
                'dia_chi_chi_tiet' => '106 Quang Trung',
                'latitude' => 16.074218,
                'longitude' => 108.225809,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 30,
                'dia_chi_chi_tiet' => '567 Dương Đình Nghệ',
                'latitude' => 16.082822,
                'longitude' => 108.23999,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 45,
                'dia_chi_chi_tiet' => '718 Đô Đốc Lân',
                'latitude' => 16.017246,
                'longitude' => 108.190329,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 25,
                'dia_chi_chi_tiet' => '508 Hoàng Diệu',
                'latitude' => 16.064057,
                'longitude' => 108.208272,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 30,
                'dia_chi_chi_tiet' => '955 Nguyễn Văn Thoại',
                'latitude' => 16.087475,
                'longitude' => 108.228281,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 5,
                'phuong_xa_id' => 36,
                'dia_chi_chi_tiet' => '755 Võ Chí Công',
                'latitude' => 16.044743,
                'longitude' => 108.22582,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 7,
                'phuong_xa_id' => 51,
                'dia_chi_chi_tiet' => '465 Quốc lộ 14B',
                'latitude' => 16.01225,
                'longitude' => 108.117346,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 2,
                'phuong_xa_id' => 13,
                'dia_chi_chi_tiet' => '647 Dũng Sĩ Thanh Khê',
                'latitude' => 16.070278,
                'longitude' => 108.183621,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 20,
                'dia_chi_chi_tiet' => '326 Nguyễn Văn Linh',
                'latitude' => 16.06409,
                'longitude' => 108.22623,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 31,
                'dia_chi_chi_tiet' => '992 Võ Nguyên Giáp',
                'latitude' => 16.095635,
                'longitude' => 108.230913,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 4,
                'phuong_xa_id' => 30,
                'dia_chi_chi_tiet' => '807 Lê Văn Thứ',
                'latitude' => 16.057496,
                'longitude' => 108.243106,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 3,
                'phuong_xa_id' => 28,
                'dia_chi_chi_tiet' => '908 Nguyễn Tri Phương',
                'latitude' => 16.074705,
                'longitude' => 108.205411,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 2,
                'phuong_xa_id' => 7,
                'dia_chi_chi_tiet' => '99 Huỳnh Ngọc Huệ',
                'latitude' => 16.064331,
                'longitude' => 108.182934,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 6,
                'phuong_xa_id' => 40,
                'dia_chi_chi_tiet' => '836 Võ An Ninh',
                'latitude' => 16.023069,
                'longitude' => 108.214175,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tinh_id' => 1,
                'quan_id' => 1,
                'phuong_xa_id' => 3,
                'dia_chi_chi_tiet' => '592 Hoàng Văn Thái',
                'latitude' => 16.095159,
                'longitude' => 108.175081,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
