<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class KhachHangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('khach_hangs')->insertOrIgnore([
            [
                'ten' => 'Võ Mai Ngọc',
                'email' => 'ngicvo881@gmail.com',
                'so_dien_thoai' => '0961788043',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Đức Việt',
                'email' => 'leducviet950@gmail.com',
                'so_dien_thoai' => '0361684421',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hoàng Hoàng Khoa',
                'email' => 'khoahoang481@gmail.com',
                'so_dien_thoai' => '0834973745',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lâm Hữu Minh',
                'email' => 'lamhuuminh131@gmail.com',
                'so_dien_thoai' => '0918172918',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trần Kim Lan',
                'email' => 'trankimlan611@gmail.com',
                'so_dien_thoai' => '0968583398',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Võ Nhật Châu',
                'email' => 'vonhatchau95@gmail.com',
                'so_dien_thoai' => '0905592761',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trần Đức Khoa',
                'email' => 'khoatran622@gmail.com',
                'so_dien_thoai' => '0778630513',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Cao Thu Hoa',
                'email' => 'hoacao927@gmail.com',
                'so_dien_thoai' => '0820104127',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đỗ Kim My',
                'email' => 'mydo315@gmail.com',
                'so_dien_thoai' => '0347422798',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Võ Kim Linh',
                'email' => 'linhvo718@gmail.com',
                'so_dien_thoai' => '0760498869',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Phương Ngân',
                'email' => 'buiphuongngan510@gmail.com',
                'so_dien_thoai' => '0912254065',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Tuấn Huy',
                'email' => 'buituanhuy189@gmail.com',
                'so_dien_thoai' => '0852932487',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đặng Nhật Long',
                'email' => 'longdang463@gmail.com',
                'so_dien_thoai' => '0705622299',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phạm Hồng Nhi',
                'email' => 'phamhongnhi676@gmail.com',
                'so_dien_thoai' => '0900360979',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Thanh Tâm',
                'email' => 'ngothanhtam997@gmail.com',
                'so_dien_thoai' => '0837487135',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Thị Vy',
                'email' => 'lethivy617@gmail.com',
                'so_dien_thoai' => '0330982808',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hồ Thành Việt',
                'email' => 'hothanhviet562@gmail.com',
                'so_dien_thoai' => '0351422697',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Bích Hoa',
                'email' => 'hoango586@gmail.com',
                'so_dien_thoai' => '0981019855',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lý Gia Huy',
                'email' => 'lygiahuy47@gmail.com',
                'so_dien_thoai' => '0376565150',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Xuân Hương',
                'email' => 'truongxuanhuong159@gmail.com',
                'so_dien_thoai' => '0370306246',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trần Hoàng Bảo',
                'email' => 'baotran213@gmail.com',
                'so_dien_thoai' => '0387592131',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Dương Thảo Hân',
                'email' => 'handuong310@gmail.com',
                'so_dien_thoai' => '0760701594',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đặng Xuân Ngân',
                'email' => 'ngandang367@gmail.com',
                'so_dien_thoai' => '0708018566',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Võ Tuấn Nam',
                'email' => 'namvo956@gmail.com',
                'so_dien_thoai' => '0980432175',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Diễm Vy',
                'email' => 'buidiemvy294@gmail.com',
                'so_dien_thoai' => '0397985758',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Thanh My',
                'email' => 'huunhthanhmy927@gmail.com',
                'so_dien_thoai' => '0384930726',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phạm Kim Nhung',
                'email' => 'phamkimnhung362@gmail.com',
                'so_dien_thoai' => '0968971905',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Diễm Hoa',
                'email' => 'hoale701@gmail.com',
                'so_dien_thoai' => '0792632485',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đỗ Khánh Ngọc',
                'email' => 'ngicdo395@gmail.com',
                'so_dien_thoai' => '0982808846',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đặng Tuấn Khang',
                'email' => 'dangtuankhang196@gmail.com',
                'so_dien_thoai' => '0392143549',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Võ Hải Nam',
                'email' => 'vohainam695@gmail.com',
                'so_dien_thoai' => '0760784498',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Mai Nhung',
                'email' => 'nhungbui300@gmail.com',
                'so_dien_thoai' => '0936947907',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hoàng Nhật Khang',
                'email' => 'hoangnhatkhang184@gmail.com',
                'so_dien_thoai' => '0364606038',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Thị Linh',
                'email' => 'linhngo363@gmail.com',
                'so_dien_thoai' => '0962395832',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Vũ Tuấn Bảo',
                'email' => 'vutuanbao913@gmail.com',
                'so_dien_thoai' => '0340765657',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lâm Hoài Tâm',
                'email' => 'tamlam590@gmail.com',
                'so_dien_thoai' => '0793110989',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Nguyễn Thái Kiệt',
                'email' => 'kietnguyen136@gmail.com',
                'so_dien_thoai' => '0382116917',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hoàng Bảo Đạt',
                'email' => 'dathoang939@gmail.com',
                'so_dien_thoai' => '0920618799',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Cao Gia Châu',
                'email' => 'caogiachau778@gmail.com',
                'so_dien_thoai' => '0700716775',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Hữu Kiệt',
                'email' => 'truonghuukiet750@gmail.com',
                'so_dien_thoai' => '0381177762',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phan Hoàng Khang',
                'email' => 'khangphan92@gmail.com',
                'so_dien_thoai' => '0358729354',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Hoài Anh',
                'email' => 'anhtruong798@gmail.com',
                'so_dien_thoai' => '0333661477',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phan Minh Kiệt',
                'email' => 'kietphan599@gmail.com',
                'so_dien_thoai' => '0370519566',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Nguyễn Quang Long',
                'email' => 'longnguyen10@gmail.com',
                'so_dien_thoai' => '0856582081',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phạm Hoàng Tùng',
                'email' => 'tungpham313@gmail.com',
                'so_dien_thoai' => '0382153793',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hồ Quang Khoa',
                'email' => 'khoaho134@gmail.com',
                'so_dien_thoai' => '0930736890',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Mai Nhung',
                'email' => 'nhunghuunh109@gmail.com',
                'so_dien_thoai' => '0972774508',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Thành Anh',
                'email' => 'buithanhanh172@gmail.com',
                'so_dien_thoai' => '0335463095',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Bảo Khoa',
                'email' => 'truongbaokhoa434@gmail.com',
                'so_dien_thoai' => '0829629261',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lâm Quốc Việt',
                'email' => 'vietlam894@gmail.com',
                'so_dien_thoai' => '0835299251',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Cao Bích Quyên',
                'email' => 'caobichquyen148@gmail.com',
                'so_dien_thoai' => '0820052996',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Hồng Hương',
                'email' => 'huunhhonghuong253@gmail.com',
                'so_dien_thoai' => '0355138813',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lý Quốc Đạt',
                'email' => 'lyquocdat218@gmail.com',
                'so_dien_thoai' => '0909053597',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đỗ Bảo Long',
                'email' => 'longdo659@gmail.com',
                'so_dien_thoai' => '0938299892',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phạm Công Khang',
                'email' => 'phamcongkhang342@gmail.com',
                'so_dien_thoai' => '0389773784',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lâm Quang Châu',
                'email' => 'lamquangchau962@gmail.com',
                'so_dien_thoai' => '0396043698',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lâm Hoàng Việt',
                'email' => 'vietlam605@gmail.com',
                'so_dien_thoai' => '0342177481',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Vũ Thảo Hân',
                'email' => 'vuthaohan408@gmail.com',
                'so_dien_thoai' => '0374031672',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Vũ Hồng Thủy',
                'email' => 'vuhongthuy538@gmail.com',
                'so_dien_thoai' => '0360552985',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phan Kim Nhung',
                'email' => 'phankimnhung247@gmail.com',
                'so_dien_thoai' => '0843948414',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hồ Thu My',
                'email' => 'myho671@gmail.com',
                'so_dien_thoai' => '0822427472',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đặng Minh Đạt',
                'email' => 'datdang237@gmail.com',
                'so_dien_thoai' => '0977501083',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Vũ Mai Linh',
                'email' => 'vumailinh480@gmail.com',
                'so_dien_thoai' => '0779514570',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Võ Hữu Kiệt',
                'email' => 'vohuukiet906@gmail.com',
                'so_dien_thoai' => '0338266626',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Nguyễn Thành Cường',
                'email' => 'nguyenthanhcuong672@gmail.com',
                'so_dien_thoai' => '0939622920',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trần Quốc Khang',
                'email' => 'khangtran527@gmail.com',
                'so_dien_thoai' => '0336099467',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Hồng Vy',
                'email' => 'lehongvy296@gmail.com',
                'so_dien_thoai' => '0988102759',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phạm Kim Linh',
                'email' => 'phamkimlinh360@gmail.com',
                'so_dien_thoai' => '0340707547',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Nguyễn Cẩm Trang',
                'email' => 'trangnguyen265@gmail.com',
                'so_dien_thoai' => '0336088965',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Đức Phát',
                'email' => 'buiducphat489@gmail.com',
                'so_dien_thoai' => '0334364545',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Hoàng Kiệt',
                'email' => 'kietbui661@gmail.com',
                'so_dien_thoai' => '0763413116',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phạm Văn Việt',
                'email' => 'vietpham278@gmail.com',
                'so_dien_thoai' => '0810065131',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Ngọc My',
                'email' => 'myngo165@gmail.com',
                'so_dien_thoai' => '0362187566',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Hoài Vy',
                'email' => 'vyhuunh248@gmail.com',
                'so_dien_thoai' => '0347788595',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Hồng Thủy',
                'email' => 'ngohongthuy326@gmail.com',
                'so_dien_thoai' => '0887749955',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lâm Hoài Nhi',
                'email' => 'nhilam258@gmail.com',
                'so_dien_thoai' => '0394555927',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Xuân Nhung',
                'email' => 'nhunghuunh377@gmail.com',
                'so_dien_thoai' => '0365160635',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Hoàng Châu',
                'email' => 'buihoangchau351@gmail.com',
                'so_dien_thoai' => '0774566534',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Phương Vy',
                'email' => 'vyhuunh208@gmail.com',
                'so_dien_thoai' => '0764362880',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Hữu Long',
                'email' => 'longngo386@gmail.com',
                'so_dien_thoai' => '0851628931',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Công Long',
                'email' => 'leconglong786@gmail.com',
                'so_dien_thoai' => '0320132520',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lý Tuấn Thịnh',
                'email' => 'thinhly268@gmail.com',
                'so_dien_thoai' => '0815934662',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hoàng Quốc Huy',
                'email' => 'huyhoang935@gmail.com',
                'so_dien_thoai' => '0967862982',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Nguyễn Hồng Trang',
                'email' => 'trangnguyen298@gmail.com',
                'so_dien_thoai' => '0818333472',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hồ Bích Hân',
                'email' => 'hobichhan417@gmail.com',
                'so_dien_thoai' => '0921368329',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Ngọc Linh',
                'email' => 'linhle11@gmail.com',
                'so_dien_thoai' => '0937283866',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hồ Kim Hương',
                'email' => 'huongho263@gmail.com',
                'so_dien_thoai' => '0702320318',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hoàng Quang Nam',
                'email' => 'namhoang935@gmail.com',
                'so_dien_thoai' => '0774890673',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hồ Bảo Khoa',
                'email' => 'khoaho697@gmail.com',
                'so_dien_thoai' => '0947301903',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lý Quang Huy',
                'email' => 'lyquanghuy256@gmail.com',
                'so_dien_thoai' => '0985231964',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Vũ Hoàng Đạt',
                'email' => 'datvu365@gmail.com',
                'so_dien_thoai' => '0794264543',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Hoàng Huy',
                'email' => 'huyhuunh886@gmail.com',
                'so_dien_thoai' => '0793978958',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Mai Lan',
                'email' => 'lanhuunh574@gmail.com',
                'so_dien_thoai' => '0936704518',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phan Thanh Lan',
                'email' => 'phanthanhlan481@gmail.com',
                'so_dien_thoai' => '0838987101',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Cao Diễm Ngân',
                'email' => 'ngancao909@gmail.com',
                'so_dien_thoai' => '0880728396',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trần Quang Tùng',
                'email' => 'tranquangtung320@gmail.com',
                'so_dien_thoai' => '0948129284',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Tuấn Tùng',
                'email' => 'tungtruong509@gmail.com',
                'so_dien_thoai' => '0821722337',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Dương Hoàng Cường',
                'email' => 'cuongduong585@gmail.com',
                'so_dien_thoai' => '0339410489',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Vũ Mai Vy',
                'email' => 'vumaivy798@gmail.com',
                'so_dien_thoai' => '0979269453',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phan Thành Minh',
                'email' => 'phanthanhminh893@gmail.com',
                'so_dien_thoai' => '0947284572',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phan Bảo Khoa',
                'email' => 'khoaphan67@gmail.com',
                'so_dien_thoai' => '0349810645',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Thái Cường',
                'email' => 'cuongle760@gmail.com',
                'so_dien_thoai' => '0395146513',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phan Kim Hoa',
                'email' => 'hoaphan671@gmail.com',
                'so_dien_thoai' => '0364837787',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trần Thị Lan',
                'email' => 'lantran47@gmail.com',
                'so_dien_thoai' => '0773157654',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Cao Khánh Vy',
                'email' => 'caokhanhvy155@gmail.com',
                'so_dien_thoai' => '0962113961',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phạm Nhật Kiệt',
                'email' => 'phamnhatkiet952@gmail.com',
                'so_dien_thoai' => '0888977029',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Nhật Khang',
                'email' => 'khangle980@gmail.com',
                'so_dien_thoai' => '0366313913',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Dương Công Tùng',
                'email' => 'tungduong907@gmail.com',
                'so_dien_thoai' => '0934552839',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đỗ Thị Vy',
                'email' => 'vydo151@gmail.com',
                'so_dien_thoai' => '0337049948',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Ngọc Nhung',
                'email' => 'truongngicnhung14@gmail.com',
                'so_dien_thoai' => '0974274161',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Nguyễn Phương Lan',
                'email' => 'lannguyen422@gmail.com',
                'so_dien_thoai' => '0790064658',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đỗ Minh Minh',
                'email' => 'dominhminh847@gmail.com',
                'so_dien_thoai' => '0845233391',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Vũ Xuân Ngọc',
                'email' => 'ngicvu120@gmail.com',
                'so_dien_thoai' => '0985294214',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Vũ Thanh Trang',
                'email' => 'vuthanhtrang341@gmail.com',
                'so_dien_thoai' => '0978498322',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Xuân Vy',
                'email' => 'vyhuunh506@gmail.com',
                'so_dien_thoai' => '0384521177',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Thảo Hương',
                'email' => 'truongthaohuong719@gmail.com',
                'so_dien_thoai' => '0902047687',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Bích Hoa',
                'email' => 'truongbichhoa215@gmail.com',
                'so_dien_thoai' => '0944157814',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hồ Thị Anh',
                'email' => 'hothianh90@gmail.com',
                'so_dien_thoai' => '0911273273',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Hải Anh',
                'email' => 'buihaianh975@gmail.com',
                'so_dien_thoai' => '0972451295',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Xuân Vy',
                'email' => 'vyngo999@gmail.com',
                'so_dien_thoai' => '0919911912',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Ngọc Trang',
                'email' => 'buingictrang71@gmail.com',
                'so_dien_thoai' => '0931974518',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Phương Linh',
                'email' => 'linhngo899@gmail.com',
                'so_dien_thoai' => '0329351323',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Hồng Nhi',
                'email' => 'nhihuunh669@gmail.com',
                'so_dien_thoai' => '0881213441',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lâm Tuấn Thịnh',
                'email' => 'lamtuanthinh862@gmail.com',
                'so_dien_thoai' => '0355300322',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đỗ Gia Nam',
                'email' => 'namdo632@gmail.com',
                'so_dien_thoai' => '0706299055',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Hải Khang',
                'email' => 'khangle923@gmail.com',
                'so_dien_thoai' => '0909898784',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hoàng Hoài Vy',
                'email' => 'hoanghoaivy936@gmail.com',
                'so_dien_thoai' => '0767350695',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phan Thái Minh',
                'email' => 'minhphan648@gmail.com',
                'so_dien_thoai' => '0707564902',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hoàng Khánh Anh',
                'email' => 'anhhoang204@gmail.com',
                'so_dien_thoai' => '0372757327',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lâm Thảo Quyên',
                'email' => 'lamthaoquyen736@gmail.com',
                'so_dien_thoai' => '0962603709',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Hồng Linh',
                'email' => 'lehonglinh571@gmail.com',
                'so_dien_thoai' => '0908737644',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Cao Phương Hương',
                'email' => 'caophuonghuong137@gmail.com',
                'so_dien_thoai' => '0358546171',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phan Cẩm Ngân',
                'email' => 'nganphan446@gmail.com',
                'so_dien_thoai' => '0769364130',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Quốc Thịnh',
                'email' => 'buiquocthinh798@gmail.com',
                'so_dien_thoai' => '0988576544',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trần Bảo Tùng',
                'email' => 'tungtran910@gmail.com',
                'so_dien_thoai' => '0966934280',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Hoàng Nam',
                'email' => 'buihoangnam698@gmail.com',
                'so_dien_thoai' => '0834963651',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hồ Quang Việt',
                'email' => 'hoquangviet835@gmail.com',
                'so_dien_thoai' => '0933635053',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đỗ Thái Châu',
                'email' => 'dothaichau969@gmail.com',
                'so_dien_thoai' => '0348285065',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Vũ Văn Cường',
                'email' => 'cuongvu931@gmail.com',
                'so_dien_thoai' => '0389630855',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Võ Minh Khang',
                'email' => 'khangvo515@gmail.com',
                'so_dien_thoai' => '0857036524',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lâm Minh Minh',
                'email' => 'lamminhminh670@gmail.com',
                'so_dien_thoai' => '0904654606',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lý Tuấn Phong',
                'email' => 'phongly753@gmail.com',
                'so_dien_thoai' => '0336780176',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Hoàng Kiệt',
                'email' => 'lehoangkiet383@gmail.com',
                'so_dien_thoai' => '0390520208',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Xuân Linh',
                'email' => 'linhhuunh387@gmail.com',
                'so_dien_thoai' => '0905867688',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hoàng Tuấn Đạt',
                'email' => 'dathoang263@gmail.com',
                'so_dien_thoai' => '0973708012',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phạm Xuân Hương',
                'email' => 'phamxuanhuong820@gmail.com',
                'so_dien_thoai' => '0914602629',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Bích Lan',
                'email' => 'lanngo738@gmail.com',
                'so_dien_thoai' => '0394859262',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Văn Anh',
                'email' => 'anhtruong767@gmail.com',
                'so_dien_thoai' => '0814519080',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lý Minh Nam',
                'email' => 'namly624@gmail.com',
                'so_dien_thoai' => '0339800094',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Hoài Anh',
                'email' => 'anhngo798@gmail.com',
                'so_dien_thoai' => '0397844830',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Thảo Hoa',
                'email' => 'ngothaohoa752@gmail.com',
                'so_dien_thoai' => '0391520350',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Minh Cường',
                'email' => 'buiminhcuong598@gmail.com',
                'so_dien_thoai' => '0851487107',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Bích Hương',
                'email' => 'huongtruong689@gmail.com',
                'so_dien_thoai' => '0835639346',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Dương Tuấn Long',
                'email' => 'longduong206@gmail.com',
                'so_dien_thoai' => '0853611410',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hoàng Thị Lan',
                'email' => 'lanhoang353@gmail.com',
                'so_dien_thoai' => '0820422848',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Minh Khoa',
                'email' => 'truongminhkhoa233@gmail.com',
                'so_dien_thoai' => '0322585358',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Xuân Linh',
                'email' => 'linhhuunh667@gmail.com',
                'so_dien_thoai' => '0781148395',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Bảo Nam',
                'email' => 'nambui458@gmail.com',
                'so_dien_thoai' => '0343041440',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Ngọc Quyên',
                'email' => 'quyentruong363@gmail.com',
                'so_dien_thoai' => '0373275983',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Khánh Hân',
                'email' => 'huunhkhanhhan37@gmail.com',
                'so_dien_thoai' => '0943629065',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Nguyễn Thái Phát',
                'email' => 'phatnguyen173@gmail.com',
                'so_dien_thoai' => '0839104251',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Khánh Hân',
                'email' => 'lekhanhhan645@gmail.com',
                'so_dien_thoai' => '0974808198',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Minh Châu',
                'email' => 'buiminhchau527@gmail.com',
                'so_dien_thoai' => '0980186232',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phạm Thảo Anh',
                'email' => 'phamthaoanh820@gmail.com',
                'so_dien_thoai' => '0700010481',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Cẩm Nhung',
                'email' => 'huunhcamnhung894@gmail.com',
                'so_dien_thoai' => '0945154135',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đỗ Hải Việt',
                'email' => 'dohaiviet417@gmail.com',
                'so_dien_thoai' => '0782756356',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Nhật Khoa',
                'email' => 'truongnhatkhoa313@gmail.com',
                'so_dien_thoai' => '0340179186',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Ngọc Anh',
                'email' => 'anhbui574@gmail.com',
                'so_dien_thoai' => '0704526507',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Võ Minh Anh',
                'email' => 'vominhanh765@gmail.com',
                'so_dien_thoai' => '0813466440',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lâm Cẩm Nhi',
                'email' => 'lamcamnhi98@gmail.com',
                'so_dien_thoai' => '0980462443',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Dương Kim Hương',
                'email' => 'huongduong380@gmail.com',
                'so_dien_thoai' => '0378505359',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trần Xuân Hoa',
                'email' => 'tranxuanhoa639@gmail.com',
                'so_dien_thoai' => '0855745835',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Thảo Ngân',
                'email' => 'truongthaongan704@gmail.com',
                'so_dien_thoai' => '0921432949',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lâm Quang Phát',
                'email' => 'lamquangphat981@gmail.com',
                'so_dien_thoai' => '0778955458',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phạm Công Bảo',
                'email' => 'baopham806@gmail.com',
                'so_dien_thoai' => '0812038671',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lâm Đức Long',
                'email' => 'longlam573@gmail.com',
                'so_dien_thoai' => '0976239382',
                'password' => bcrypt('123456789'),
                'is_active' => false,
                'trang_thai' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Thu Quyên',
                'email' => 'buithuquyen320@gmail.com',
                'so_dien_thoai' => '0322380649',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Hồng Nhung',
                'email' => 'nhunghuunh803@gmail.com',
                'so_dien_thoai' => '0848561981',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Công Huy',
                'email' => 'huyle832@gmail.com',
                'so_dien_thoai' => '0708067596',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Vũ Công Phong',
                'email' => 'vucongphong841@gmail.com',
                'so_dien_thoai' => '0795718974',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Thảo Nhi',
                'email' => 'nhihuunh271@gmail.com',
                'so_dien_thoai' => '0933102533',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lê Gia Bảo',
                'email' => 'legiabao316@gmail.com',
                'so_dien_thoai' => '0327175971',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lý Thảo Hương',
                'email' => 'huongly395@gmail.com',
                'so_dien_thoai' => '0825940070',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Xuân My',
                'email' => 'ngoxuanmy184@gmail.com',
                'so_dien_thoai' => '0365671725',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đặng Thanh Ngân',
                'email' => 'dangthanhngan318@gmail.com',
                'so_dien_thoai' => '0768736137',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lý Xuân Tâm',
                'email' => 'lyxuantam726@gmail.com',
                'so_dien_thoai' => '0903556338',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Diễm My',
                'email' => 'mybui171@gmail.com',
                'so_dien_thoai' => '0396221029',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đặng Hải Đạt',
                'email' => 'datdang900@gmail.com',
                'so_dien_thoai' => '0393027404',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Hoàng Phát',
                'email' => 'truonghoangphat997@gmail.com',
                'so_dien_thoai' => '0765676262',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Huỳnh Thảo Tâm',
                'email' => 'tamhuunh502@gmail.com',
                'so_dien_thoai' => '0988336028',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Lý Gia Thịnh',
                'email' => 'thinhly647@gmail.com',
                'so_dien_thoai' => '0967071660',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hồ Thanh Linh',
                'email' => 'hothanhlinh97@gmail.com',
                'so_dien_thoai' => '0827058311',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Đặng Hồng Vy',
                'email' => 'vydang305@gmail.com',
                'so_dien_thoai' => '0900300915',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Ngô Hoàng Huy',
                'email' => 'ngohoanghuy423@gmail.com',
                'so_dien_thoai' => '0390398442',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Nhật Khoa',
                'email' => 'truongnhatkhoa713@gmail.com',
                'so_dien_thoai' => '0342616808',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Bùi Công Nam',
                'email' => 'buicongnam267@gmail.com',
                'so_dien_thoai' => '0833815004',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Phạm Minh Tùng',
                'email' => 'phamminhtung733@gmail.com',
                'so_dien_thoai' => '0365521279',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Hoàng Kim Hương',
                'email' => 'huonghoang139@gmail.com',
                'so_dien_thoai' => '0361471200',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Trương Gia Thịnh',
                'email' => 'thinhtruong30@gmail.com',
                'so_dien_thoai' => '0835800340',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten' => 'Dương Công Kiệt',
                'email' => 'duongcongkiet64@gmail.com',
                'so_dien_thoai' => '0837176086',
                'password' => bcrypt('123456789'),
                'is_active' => true,
                'trang_thai' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
